#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page.
REDIRECT="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; \n\t}\n"
FILE="/etc/nginx/sites-available/default"
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
mkdir -p /var/www/html/
sudo chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.html
sed -i "37i\ $REDIRECT" "$FILE"
service nginx restart

