#!/usr/bin/env bash
#Configure your Nginx so that its  HTTP response contains a custom header (on web-01 and web-02)

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html /var/www/error
sudo chmod -R 755 /var/www
sudo echo 'Hello World!' | sudo tee /var/www/html/index.html
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
server_config=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	add_header X-Served-By \$hostname;
	location / {
		try_files \$uri \$uri/ =404;
	}
}"
echo "$server_config" > /etc/nginx/sites-enabled/default
sudo service nginx restart
