#!/usr/bin/env bash
#This script displaying he time for 12 hours and 59 minutes:
#display hours from 0 to 12
#display minutes from 1 to 59
hours=0
while [ $hours -lt 13 ]
do 
	echo "Hours : $hours"
	minutes=1
	while [ $minutes -lt 60 ]
	do
		echo $minutes
		((minutes++))
	done
	((hours++))
done
