#!/usr/bin/env bash
# This script gives you information about the school file.
file="school"

# Check if file exists
if [ -e $file ]; then
    echo "school file exists"
    # Check if file is empty
    if [ -s $file ]; then
        echo "school file is not empty"
        # Check if file is a regular file
        if [ -f $file ]; then
            echo "school is a regular file"
        fi
    else
        echo "school file is empty"
    fi
else
    echo "school file does not exist"
fi
